name: etl_environment
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - apscheduler=3.11.0=pyh29332c3_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=h2970c50_0
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.1=hcb3a2da_9
  - aws-c-event-stream=0.5.7=ha388e84_1
  - aws-c-http=0.10.7=hc678f4a_5
  - aws-c-io=0.23.3=h0d5b9f9_5
  - aws-c-mqtt=0.13.3=hfa314fa_11
  - aws-c-s3=0.11.3=ha659bf3_1
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.7=hcb3a2da_5
  - aws-crt-cpp=0.35.4=hca034e6_0
  - aws-sdk-cpp=1.11.606=hac16450_10
  - azure-core-cpp=1.16.2=h49e36cd_0
  - azure-identity-cpp=1.13.3=h5ffce34_1
  - azure-storage-blobs-cpp=12.16.0=hcd625b1_1
  - azure-storage-common-cpp=12.12.0=h5ffce34_1
  - azure-storage-files-datalake-cpp=12.14.0=h1678c0b_1
  - backports.zstd=1.3.0=py314h680f03e_0
  - blosc=1.21.6=hfd34d9b_1
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py314he701e3d_1
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py314hf309875_4
  - cpython=3.14.3=py314hd8ed1ab_101
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.20=py314hb98de8c_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - fiona=1.10.1=py314h1c1cb05_6
  - folium=0.20.0=pyhd8ed1ab_0
  - fonttools=4.61.1=pyh7db6752_0
  - freetype=2.14.1=h57928b3_0
  - freexl=2.0.0=hf297d47_2
  - geoalchemy2=0.18.1=pyhd8ed1ab_0
  - geopandas=1.1.2=pyhd8ed1ab_0
  - geopandas-base=1.1.2=pyha770c72_0
  - geos=3.14.1=hdade9fe_0
  - greenlet=3.3.1=py314hb98de8c_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - ipykernel=7.2.0=pyh6dadd2b_1
  - ipython=9.10.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - joblib=1.5.3=pyhd8ed1ab_0
  - jupyter_client=8.8.0=pyhcf101f3_0
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py314hf309875_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20260107.0=cxx17_h0eb2380_0
  - libarchive=3.8.5=gpl_he24518a_100
  - libarrow=23.0.0=hde9e798_3_cpu
  - libarrow-acero=23.0.0=h7d8d6a5_3_cpu
  - libarrow-compute=23.0.0=h081cd8e_3_cpu
  - libarrow-dataset=23.0.0=h7d8d6a5_3_cpu
  - libarrow-substrait=23.0.0=h524e9bd_3_cpu
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.18.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_17
  - libgdal-core=3.12.2=h9774fe2_0
  - libgomp=15.2.0=h8ee18e1_17
  - libgoogle-cloud=2.39.0=h01c467a_1
  - libgoogle-cloud-storage=2.39.0=he04ea4c_1
  - libgrpc=1.78.0=h9ff2b3e_1
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.2=hf3f85d1_0
  - libkml=1.3.0=h68a222c_1022
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libmpdec=4.0.0=hfd05255_1
  - libparquet=23.0.0=h7051d1f_3_cpu
  - libpng=1.6.55=h7351971_0
  - libpq=18.1=h9e1d4a5_3
  - libprotobuf=6.33.5=h61fc761_0
  - libre2-11=2025.11.05=h04e5de1_1
  - librttopo=1.1.0=haa95264_20
  - libsodium=1.0.20=hc70643c_0
  - libspatialite=5.1.0=gpl_h0cd62ae_119
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h8f73337_1
  - libutf8proc=2.11.3=hb980946_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxml2-devel=2.15.1=h779ef1b_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - markupsafe=3.0.3=pyh7db6752_0
  - matplotlib-base=3.10.8=py314hfa45d96_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - minizip=4.0.10=h9fa1bad_0
  - mkl=2025.3.0=hac47afa_455
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=he0c23c2_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.6.1=pyhcf101f3_0
  - numpy=2.4.2=py314h06c3c77_1
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.1=hf411b9b_1
  - orc=2.2.2=h0a1ad0e_1
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py314hf700ef7_0
  - parso=0.8.6=pyhcf101f3_0
  - pcre2=10.47=hd2b5f0e_0
  - pillow=12.1.1=py314h61b30b5_0
  - pip=26.0.1=pyh145f28c_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - proj=9.7.1=hd30e2cd_2
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.2.2=py314hc5dbbe4_0
  - psycopg2=2.9.11=py314h3cd40a6_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow-core=23.0.0=py314h159fc0c_0_cpu
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyogrio=0.12.1=py314h1c1cb05_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyproj=3.7.2=py314h422fe16_2
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.14.3=h4b44e0e_101_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.14.3=h4df99d1_101
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.14=8_cp314
  - pywin32=311=py314h8f8f202_1
  - pyyaml=6.0.3=py314h2359020_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - qhull=2020.2=hc790b64_5
  - re2=2025.11.05=ha104f34_1
  - requests=2.32.5=pyhcf101f3_1
  - scikit-learn=1.8.0=np2py314h1b5b07a_1
  - setuptools=82.0.0=pyh332efcf_0
  - shapely=2.1.2=py314h76f3c27_2
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - sqlalchemy=2.0.46=py314hc5dbbe4_1
  - sqlite=3.51.2=hdb435a2_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=h3155e25_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h6ed50ae_3
  - tornado=6.5.4=py314h5a2d7ad_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - tzlocal=5.3.1=pyha7b4d00_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py314h5a2d7ad_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - wcwidth=0.6.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xerces-c=3.3.0=hac47afa_1
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h6a83c73_3
  - zeromq=4.3.5=h5bddc39_9
  - zlib=1.3.1=h2466b09_2
  - zlib-ng=2.3.3=h0261ad2_1
  - zstd=1.5.7=h534d264_6
  - pip:
      - pyarrow==23.0.0
      - scipy==1.17.0
prefix: C:\Users\Acer\miniforge3\envs\etl_environment
