name: api_environment
channels:
  - conda-forge
dependencies:
  - backports.zstd=1.3.0=py314h680f03e_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py314h58356db_1
  - bzip2=1.0.8=h0ad9c76_9
  - ca-certificates=2026.1.4=h4c7d964_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.1=pyha7b4d00_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - flask=3.1.3=pyhcf101f3_1
  - flask-cors=6.0.2=pyhcf101f3_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h637d24d_0
  - idna=3.11=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - krb5=1.21.3=hdf4eb48_0
  - libexpat=2.7.4=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - liblzma=5.8.2=hfd05255_0
  - libmpdec=4.0.0=hfd05255_1
  - libpq=18.2=h9e1d4a5_0
  - libsqlite=3.51.2=hf5d6505_0
  - libzlib=1.3.1=h2466b09_2
  - markupsafe=3.0.3=pyh7db6752_0
  - openssl=3.6.1=hf411b9b_1
  - pip=26.0.1=pyh145f28c_0
  - psycopg2=2.9.11=py314h7b6b9a3_0
  - psycopg2-binary=2.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.14.3=h7c1dbca_1_cp314t
  - python_abi=3.14=8_cp314t
  - requests=2.32.5=pyhcf101f3_1
  - tk=8.6.13=h6ed50ae_3
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - werkzeug=3.1.6=pyhcf101f3_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - zstd=1.5.7=h534d264_6
prefix: C:\Users\Acer\miniforge3\envs\api_environment
